package jobs

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"syscall"
	"time"

	"github.com/jstamagal/bitchtea/internal/daemon"
)

// staleCleanupArgs is the wire shape of a stale-cleanup job's Args.
//
// session_dir is the directory the daemon scans for stale .jsonl session
// logs. archive_dir is where any session whose mtime is older than the
// cutoff gets relocated to. max_age_days computes that cutoff:
//
//	cutoff = now - max_age_days * 24h
//	archive any *.jsonl whose mtime < cutoff
//
// max_age_days must be >= 0; a negative value is treated as a configuration
// error rather than silently meaning "future" because it almost always
// indicates the caller miscomputed an age.
//
// Sidecars like .bitchtea_checkpoint.json that live next to the JSONL are
// intentionally NOT moved — they're regenerated by session-checkpoint and
// scoped to whatever session is currently active, so leaving them in place
// keeps the behavior predictable when a user later resumes a non-archived
// session in the same directory.
type staleCleanupArgs struct {
	SessionDir  string `json:"session_dir"`
	ArchiveDir  string `json:"archive_dir"`
	MaxAgeDays  int    `json:"max_age_days"`
}

// staleCleanupOutput summarises a run.
//
//   - Scanned: total .jsonl files inspected (including ones kept).
//   - Archived: files successfully moved into ArchiveDir.
//   - Skipped: stale files that hit a destination collision and were left
//     untouched (see conflict handling below).
//   - Conflicts: basenames of the skipped files; useful diagnostic for the
//     TUI surface.
type staleCleanupOutput struct {
	Scanned   int      `json:"scanned"`
	Archived  int      `json:"archived"`
	Skipped   int      `json:"skipped"`
	Conflicts []string `json:"conflicts,omitempty"`
}

// handleStaleCleanup archives session JSONL files older than the configured
// cutoff into a sibling archive directory.
//
// Idempotency: archival is implemented as os.Rename (with a copy+remove
// fallback for cross-filesystem moves). After a successful run the source
// file no longer exists in session_dir, so a re-run with the same cutoff
// finds nothing new to archive — final on-disk state is identical to a
// single run. Destination collisions (a file with the same basename already
// in archive_dir) are never overwritten; they are recorded as conflicts and
// the source file is left in place so the operator can investigate.
//
// Bound: 60s context. Listing a sessions directory and renaming files is
// cheap, but we want a hard ceiling so a hung filesystem doesn't pin a
// daemon worker.
//
// Cancellation: ctx.Err() is checked before the directory listing and
// between every per-file move so a SIGTERM-driven shutdown aborts cleanly
// without a partially-archived directory state worse than what we started
// with.
func handleStaleCleanup(ctx context.Context, job daemon.Job) daemon.Result {
	started := time.Now().UTC()
	kind := KindStaleCleanup

	ctx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	if err := ctx.Err(); err != nil {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: %w", err))
	}

	var args staleCleanupArgs
	if len(job.Args) > 0 {
		if err := json.Unmarshal(job.Args, &args); err != nil {
			return errorResult(kind, started, fmt.Errorf("stale-cleanup: parse args: %w", err))
		}
	}
	if args.SessionDir == "" {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: session_dir is required"))
	}
	if args.ArchiveDir == "" {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: archive_dir is required"))
	}
	if args.MaxAgeDays < 0 {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: max_age_days must be >= 0, got %d", args.MaxAgeDays))
	}

	// Reject configurations where archive_dir lives inside session_dir —
	// the next run would rescan the archive itself, "stale" by definition,
	// and we'd recurse into an ever-deeper subdirectory layout. Resolve
	// both paths so a relative session_dir can't slip through the check.
	sessAbs, err := filepath.Abs(args.SessionDir)
	if err != nil {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: resolve session_dir: %w", err))
	}
	archAbs, err := filepath.Abs(args.ArchiveDir)
	if err != nil {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: resolve archive_dir: %w", err))
	}
	if archAbs == sessAbs {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: archive_dir must differ from session_dir"))
	}
	if rel, err := filepath.Rel(sessAbs, archAbs); err == nil && rel != "" && rel[0] != '.' {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: archive_dir %q is inside session_dir %q", args.ArchiveDir, args.SessionDir))
	}

	cutoff := started.Add(-time.Duration(args.MaxAgeDays) * 24 * time.Hour)

	candidates, err := listJSONLByName(sessAbs)
	if err != nil {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: list sessions: %w", err))
	}

	if err := ctx.Err(); err != nil {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: %w", err))
	}

	out := staleCleanupOutput{Scanned: len(candidates)}

	if len(candidates) == 0 {
		// No source dir, or no .jsonl files. Nothing to do — but make sure
		// the archive_dir exists so a downstream "is the archive populated?"
		// check doesn't fail with ENOENT just because we never archived
		// anything yet.
		if err := os.MkdirAll(archAbs, 0o755); err != nil {
			return errorResult(kind, started, fmt.Errorf("stale-cleanup: ensure archive_dir: %w", err))
		}
		return successResult(kind, started, out)
	}

	if err := os.MkdirAll(archAbs, 0o755); err != nil {
		return errorResult(kind, started, fmt.Errorf("stale-cleanup: ensure archive_dir: %w", err))
	}

	for _, src := range candidates {
		if err := ctx.Err(); err != nil {
			return errorResult(kind, started, fmt.Errorf("stale-cleanup: %w", err))
		}

		info, err := os.Stat(src)
		if err != nil {
			// File vanished between ReadDir and Stat — treat as a no-op
			// rather than a hard failure; another run will catch it.
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			return errorResult(kind, started, fmt.Errorf("stale-cleanup: stat %s: %w", src, err))
		}
		if !info.Mode().IsRegular() {
			continue
		}
		if !info.ModTime().Before(cutoff) {
			// File is fresh enough to keep.
			continue
		}

		dst := filepath.Join(archAbs, filepath.Base(src))
		if _, err := os.Stat(dst); err == nil {
			// Destination already holds a sibling with the same basename
			// (could be a previous run's archive entry, could be a manual
			// copy). Refuse to overwrite — the JSONL is append-only and
			// silently clobbering a prior archive would lose history.
			out.Skipped++
			out.Conflicts = append(out.Conflicts, filepath.Base(src))
			continue
		} else if !errors.Is(err, os.ErrNotExist) {
			return errorResult(kind, started, fmt.Errorf("stale-cleanup: stat dst %s: %w", dst, err))
		}

		if err := moveFile(src, dst); err != nil {
			return errorResult(kind, started, fmt.Errorf("stale-cleanup: move %s -> %s: %w", src, dst, err))
		}
		out.Archived++
	}

	return successResult(kind, started, out)
}

// listJSONLByName returns the absolute paths of every .jsonl file directly
// under dir, sorted by basename so the iteration order is stable across
// runs (idempotency depends on this — the conflicts list and any partial
// progress on cancellation should be deterministic). A non-existent dir
// is treated as "nothing to scan" rather than an error so a freshly
// provisioned host doesn't fail every cleanup run until the first session
// gets created.
func listJSONLByName(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if filepath.Ext(e.Name()) != ".jsonl" {
			continue
		}
		out = append(out, filepath.Join(dir, e.Name()))
	}
	sort.Strings(out)
	return out, nil
}

// moveFile relocates src to dst. We try os.Rename first (atomic when both
// paths share a filesystem) and fall back to copy + remove on EXDEV so the
// handler stays robust when callers point archive_dir at a different mount
// (e.g., archiving onto an attached volume).
func moveFile(src, dst string) error {
	if err := os.Rename(src, dst); err == nil {
		return nil
	} else if !isCrossDeviceLink(err) {
		return err
	}
	if err := copyFile(src, dst); err != nil {
		return err
	}
	if err := os.Remove(src); err != nil {
		// We already wrote dst; leaving a duplicate behind is safer than
		// reporting success when the source still lingers. Surface the
		// remove error so the operator can clean up.
		return fmt.Errorf("copied to %s but remove %s failed: %w", dst, src, err)
	}
	return nil
}

func isCrossDeviceLink(err error) bool {
	var le *os.LinkError
	if errors.As(err, &le) {
		return errors.Is(le.Err, syscall.EXDEV)
	}
	return errors.Is(err, syscall.EXDEV)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	info, err := in.Stat()
	if err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_EXCL, info.Mode().Perm())
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		_ = os.Remove(dst)
		return err
	}
	if err := out.Close(); err != nil {
		_ = os.Remove(dst)
		return err
	}
	// Preserve mtime so a future cleanup run on the archive directory
	// (should anyone configure it) keeps using the original session age,
	// not the copy time.
	if err := os.Chtimes(dst, info.ModTime(), info.ModTime()); err != nil {
		return fmt.Errorf("chtimes dst: %w", err)
	}
	return nil
}
