package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jstamagal/bitchtea/internal/tools"
)

func main() {
	update := flag.Bool("update", false, "Update docs/tools.md in-place instead of printing to stdout")
	flag.Parse()

	// Determine project root: walk up from cmd/gendocs to find go.mod.
	exe, _ := os.Executable()
	root := findRoot(exe)
	if root == "" {
		// Fallback: assume we're running from the project root.
		root = "."
	}

	reg := tools.NewRegistry(root, filepath.Join(root, "sessions"))
	defs := reg.Definitions()
	sort.Slice(defs, func(i, j int) bool {
		return defs[i].Function.Name < defs[j].Function.Name
	})

	table := generateTable(defs)

	if *update {
		toolsMD := filepath.Join(root, "docs", "tools.md")
		if err := updateInPlace(toolsMD, table); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	} else {
		fmt.Print(table)
	}
}

func generateTable(defs []tools.ToolDef) string {
	var b strings.Builder
	b.WriteString("| Tool | Category | Description | Typed Wrapper |\n")
	b.WriteString("| :--- | :--- | :--- | :--- |\n")

	for _, d := range defs {
		name := "`" + d.Function.Name + "`"
		cat := category(d.Function.Name)
		desc := d.Function.Description
		tw := typedWrapperName(d.Function.Name)

		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", name, cat, desc, tw))
	}

	b.WriteString("\n")
	counts := countTyped(defs)
	b.WriteString(fmt.Sprintf("Tool counts: %d typed wrappers, %d legacy adapter.\n",
		counts.typed, counts.legacy))
	b.WriteString(fmt.Sprintf("Total: %d, matching `tools.Definitions()`.\n", len(defs)))

	return b.String()
}

type toolCounts struct{ typed, legacy int }

func countTyped(defs []tools.ToolDef) toolCounts {
	var c toolCounts
	for _, d := range defs {
		if isTyped(d.Function.Name) {
			c.typed++
		} else {
			c.legacy++
		}
	}
	return c
}

var typedTools = map[string]string{
	"read":          "typed_read.go",
	"write":         "typed_write.go",
	"edit":          "typed_edit.go",
	"bash":          "typed_bash.go",
	"search_memory": "typed_search_memory.go",
	"write_memory":  "typed_write_memory.go",
}

func isTyped(name string) bool {
	_, ok := typedTools[name]
	return ok
}

func typedWrapperName(name string) string {
	if f, ok := typedTools[name]; ok {
		return fmt.Sprintf("Yes (`%s`)", f)
	}
	return "No (legacy adapter)"
}

func category(name string) string {
	switch {
	case name == "bash":
		return "System"
	case name == "search_memory" || name == "write_memory":
		return "Memory"
	case name == "preview_image":
		return "Visual"
	case strings.HasPrefix(name, "terminal_"):
		return "Terminal"
	default:
		return "File System"
	}
}

const (
	markerStart = "<!-- AUTOGENERATED:TOOLS-TABLE -->"
	markerEnd   = "<!-- :END -->"
)

func updateInPlace(path, table string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}

	content := string(data)
	startIdx := strings.Index(content, markerStart)
	if startIdx < 0 {
		return fmt.Errorf("marker %q not found in %s", markerStart, path)
	}
	endIdx := strings.Index(content, markerEnd)
	if endIdx < 0 {
		return fmt.Errorf("marker %q not found in %s", markerEnd, path)
	}
	if endIdx <= startIdx+len(markerStart) {
		return fmt.Errorf("markers out of order in %s", path)
	}

	// Find end of markerStart line.
	startLineEnd := startIdx + len(markerStart)
	// Find start of markerEnd line.
	endLineStart := endIdx

	before := content[:startLineEnd]
	after := content[endLineStart:]

	newContent := before + "\n\n" + table + "\n" + after
	if err := os.WriteFile(path, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	fmt.Printf("Updated %s\n", path)
	return nil
}

// findRoot walks up from dir looking for go.mod.
func findRoot(dir string) string {
	d := dir
	for {
		if info, err := os.Stat(filepath.Join(d, "go.mod")); err == nil && !info.IsDir() {
			return d
		}
		parent := filepath.Dir(d)
		if parent == d {
			return ""
		}
		d = parent
	}
}
